baseURL = 'http://nber1994.github.io/'
languageCode = 'zh-cn'
title = "jingtianyou's blog"
#theme = "elephants"
paginate = 30

[markup]
  [markup.highlight]
    style = 'github'
    tabWidth = 4	
    codeFences = true
  [markup.goldmark.renderer]
    unsafe = true

[params]
    sitename = "nber1994"
    dateform = "2006-01-02"

[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1

  [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 2

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 3
  [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = 4
